version: "3"

volumes:
  db-data:
    external: false
  gems:
    external: false

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/db-data
    ports:
      - 5432:5432

  app:
    build: .
    entrypoint: ./docker-rails-entrypoint.sh
    env_file: .env
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    volumes:
      - gems:/usr/src/gems
      - .:/usr/src/app
    ports:
      - 4000:4000
    depends_on:
      - db
      - webpacker

  webpacker:
    build: .
    entrypoint: ./docker-webpacker-entrypoint.sh
    env_file: .env
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    volumes:
      - gems:/usr/src/gems
      - .:/usr/src/app
    ports:
      - 3035:3035
